Empty
shanemachine92/command_line_TTT pull request #1
Opened 2017-07-10 21:07 UTC by shanemachine92

2017-07-11 15:55 UTC, cbnoonan commented on models/board.rb
> +      four: ' ', five: ' ', six: ' ',
is empty string the right thing to use here?

2017-07-11 15:55 UTC, cbnoonan commented on spec/models/player_spec.rb
> +	it 'does turn' do
is this spec actually doing anything?

2017-07-11 15:55 UTC, cbnoonan commented on models/board.rb
> +    def board_rows
indent is off here

2017-07-11 15:55 UTC, cbnoonan commented on models/game.rb
> +	def initialize
initialize is generally the first method of a class

2017-07-11 15:55 UTC, cbnoonan commented on models/game.rb
> +			if @current_player == @player1
spacing is too much

2017-07-11 15:55 UTC, cbnoonan commented on models/game.rb
> +			if @current_player == @player1
what happens if you don't have @current_player as the last line of the method, would this still work?

2017-07-11 15:55 UTC, cbnoonan commented on models/game.rb
> +	def help
good idea to have a help method.

2017-07-11 15:55 UTC, cbnoonan commented on models/game.rb
> +			elsif move == 'help'
does it make sense to have move in this conditional?  Can a user just type 'help' anytime?  Maybe this should be in it's own conditional and not within the else

2017-07-11 15:55 UTC, cbnoonan commented on models/player.rb
> +  def do_turn (selected_cell)
you could make this method name a little more understandable like "take_turn" or "make_turn" which are more natural language than "do turn"

2017-07-11 15:55 UTC, cbnoonan commented on spec/models/game_spec.rb
> +	it 'has a game over status of false' do
is this test providing any value? It seems that you're just testing that you set the value in the initializer.  Maybe it would be helpful to set up a scenario, like a player takes a first move and  then test that the game is not over.

2017-07-11 15:55 UTC, cbnoonan commented on spec/models/game_spec.rb
> +		expect(@total_moves).to eq(0)
this again is just testing the values in the initializer and could provide more value

2017-07-13 21:19 UTC, ryanabooth commented on README.md
> +Dragon Age 2 themed Tic Tac Toe.
Go README!

2017-07-14 17:24 UTC, JesseBuesking requested changes
I only have a few change requests since Colleen covered most of the other code pretty thoroughly.

2017-07-14 17:24 UTC, JesseBuesking commented on models/board.rb
> +    false
Could change this to just

```
return @cells[selected_cell.to_sym] == ' '
```

Why? The result of this equality test will be a boolean. For example:

Imagine `@cells[:foo]` is the value ` `. Then this is equivalent to

```
return true if ' ' == ' '
false
```

Or

```
return true if true
else false
```

Also, because ruby will *always* return a value from a function, you don't even need the `return` keyword. Just do

```
@cells[selected_cell.to_sym] == ' '
```

2017-07-26 20:50 UTC, shanemachine92 commented on models/board.rb
> +    false
Love this. Thanks, Jesse!

2017-08-14 03:12 UTC, cbnoonan commented on models/game.rb
> +	def initialize
did you make these changes, by the way? @shanemachine92

2017-08-14 03:24 UTC, shanemachine92 commented on models/game.rb
> +	def initialize
Yes, all of these changes were made with the last commit 18 days ago.

2017-08-16 20:25 UTC, JesseBuesking approved these changes

2017-08-16 22:30 UTC, merged

2017-08-17 03:47 UTC, cbnoonan commented on models/board.rb
> +      seven: '', eight: '', nine: '',
is empty string the right thing to use here? what are other alternatives?

2017-08-17 03:47 UTC, cbnoonan commented on models/game.rb
> +	def initialize
ok awesome. I think we're going to need to do a bit more work on your git skills. :)

2017-08-17 03:51 UTC, cbnoonan reviewed
Great changes. I think we'll need to work on github skills a bit more (so these PRs don't hang out forever)  I was curious why there were a few questions asked within the code, but you didn't answer. You can always feel free to defend your code or give clarity in the PR. :)

2017-08-17 03:51 UTC, cbnoonan commented on models/game.rb
> +    @current_player
what happens if you don't have @current_player as the last line of the method, would this still work?

2017-08-17 16:05 UTC, shanemachine92 commented
@cbnoonan 
I agree! Having things thing around for so long wasn't ideal and led to a lot of confusion. Sometimes I would make changes, but wasn't sure how to let people know, so changes have gone unmerged. Is @ing them to take a look the best way to do that?

There were a few questions where I just went along and reviewed the code, making changes if/when I could, but you're right. It would be good etiquette to let people know that I've seen and addressed their questions or to defend my decisions by just responding to the thread. Great lesson!